### ISSUE TITLE
Vertical Scroll Bar doesn't reflect size of project and also scrolls the menu

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/solo#401] opened 2020-04-02 16:27 UTC
This may relate to #70 

The vertical scroll bar doesn't change to reflect the size of the project (preventing vertical scrolling of the project via the scroll bar or mouse wheel).  In addition, scroll bar is not constrained to the project editor space itself; instead it actually scrolls the menu.

Top of editor (before scroll):
![image](https://user-images.githubusercontent.com/1266318/78273666-01278280-74c4-11ea-9838-3d89af32aabf.png)

Top of editor (after scroll):
![image](https://user-images.githubusercontent.com/1266318/78273656-fbca3800-74c3-11ea-9ee7-e217668b5789.png)

NOTE: I did not change where I took the screenshot from... the cut off part at the top is exactly what the user sees.

**Comment by PropGit** [comment] 2020-04-02 16:38
Here's an example project.
[LEDToggle#2 (8).zip](https://github.com/parallaxinc/solo/files/4422306/LEDToggle.2.8.zip)

**Comment by zfi** [comment] 2020-04-02 18:55
The scrollbar is a component of the editor canvas, which is in a separate div that the UI elements in the header. It should be impossible for the scrollbar to impact the top div at all.

I tried loading the projected project on three browsers, Chrome, Firefox and Safari and am not able to reproduce the error. Let's figure out what the environment looks like, browser & OS, and also verify that the browser data cache has been purged.

**Comment by zfi** [comment] 2020-04-06 00:40
Closing this issue. Please feel free to reopen it if there is more information available.

**Closed by zfi** 2020-04-06 00:40 UTC
Labels: bug

**Comment by phil-pilgrim** [comment] 2020-04-22 02:07
So which files got changed to fix this problem? I'd like to incorporate the new ones in my repository.
