### ISSUE TITLE
Download to Flip device fails after one donwload cycle

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#452] opened 2020-06-05 15:17 UTC
Reported initially in issue #434 
I hope the update comes soon since using SoloCup keeps failing on download to Flip after compiling. It works once but then I need to restart and reconnect to Launcher (now v1.0.1)

**Comment by PropGit** [comment] 2020-06-05 15:57
@Automaxion - what OS are you using Launcher v1.0.1 on?

**Comment by Automaxion** [comment] 2020-06-06 08:07
![image](https://user-images.githubusercontent.com/65939651/83939455-82a9d280-a7dd-11ea-9d82-bdc205fea4c7.png)

**Comment by PropGit** [comment] 2020-06-06 11:38
Thank you @Automaxion.

Can you take a couple screenshots of Launcher's log view?

1. Click on the gear icon (lower-right of Launcher window)
1. Checkmark the "Verbose logging" option
1. Perform your first download
1. Perform your second download
1. Scroll back the log display and take the first screenshot
1. Scroll down the log display and take the second screenshot (it's fine, and recommended, if the log details of the two screenshots overlap a little)

I'm hoping to capture a detail there that will help me determine exactly how it's failing on the second download.

**Comment by Automaxion** [comment] 2020-06-09 19:17
I could not reproduce the problem.

**Comment by PropGit** [comment] 2020-10-29 17:45
Closing after no further information.  May still be a problem related to #514 and/or #510.

**Closed by PropGit** 2020-10-29 17:45 UTC
