### ISSUE TITLE
Feature request: choose save-as destination

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/solo#245] opened 2020-01-21 22:50 UTC
Teacher requested that we have the ability to choose a file save-as path so that code is not all put into the downloads folder.

**Comment by PropGit** [comment] 2020-01-21 22:58
Thoughts...

As far as I know, there's no ability to do that through just a web site; however, we could potentially shuffle the file data for download through a future version of BlocklyProp Launcher which would be able to manage system file access.  Making a nice interface for the user would be a challenge.  I think a better option is had if we transition the site to a PWA because I think it gives us access to the local system's file browsing capabilities at that point.

**Comment by zfi** [comment] 2020-01-22 07:20
1) This feature was removed from the app about 2 months ago.
2) Saving the project is a function on the user's browser, not the server. We'll just have to reinstate the code that was removed to correct this.

**Comment by MatzElectronics** [comment] 2020-01-22 07:50
@PropGit is correct, it's actually not possible to do this: https://stackoverflow.com/questions/34870711/download-a-file-at-different-location-using-html5

What @zfi is describing was a prompt that asked the user to specify/rename their project right before downloading, but that was redundant so we removed it - and at the time, he had a browser setting that always asked him where he wanted to download files.

The best solution for the user is to toggle this same setting in their browser (and have their students do the same.  Here is a link for instructions for changing this setting in Chrome:
https://lifehacker.com/make-chrome-ask-where-to-save-downloaded-files-by-chang-1790840372

**Comment by zfi** [comment] 2020-01-30 19:28
Confirmed that this is a browser setting. Directions for setting this should be added to the documentation.

[Chrome](https://support.google.com/chrome/answer/95759?co=GENIE.Platform%3DDesktop&hl=en)
[Firefox](https://support.mozilla.org/en-US/kb/where-find-and-manage-downloaded-files-firefox)
[Safari](https://support.apple.com/guide/safari/general-ibrw1072/mac)

**Comment by PropGit** [comment] 2020-02-14 19:10
Interestingly, the nwjs wrapper for BlocklyProp Launcher seems to enable this behaviour by default - when working within the Solo site launched by BP Launcher on Win (and probably on Mac too), the Save button opens a system file dialog.

**Comment by zfi** [comment] 2020-06-17 16:39
Closing this issue as mitigated with user browser settings.

**Closed by zfi** 2020-06-17 16:39 UTC
Labels: documentation, enhancement
