### ISSUE TITLE
X to close in new project dialog not the same as Cancel

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/solo#146] opened 2019-11-01 19:54 UTC
Cancel from the new project dialog returns you to the home page.  If you instead click X in the upper-right to close, it sends you two what looks like it might be an undefined project.

**Comment by zfi** [comment] 2019-11-01 20:01
The new project dialog is not returning to the home page if:
* A) The dialog is dismissed (clicking on the 'x') and
* B) There is not a project stashed in the browser's localStorage.

In verifying this, I also found that the intermediate dialog box that confirms that you wish to discard the existing project is no longer working as expected.

**Comment by zfi** [comment] 2019-11-12 18:32
This issue also occurs in the Open Project dialog and has the same root cause.

**Comment by zfi** [comment] 2020-01-10 19:22
Verified that dismissing the New Project dialog from the 'x' or from the Cancel button produce identical behavior.
Closing this issue.

**Closed by zfi** 2020-01-10 19:22 UTC
Labels: bug
