### ISSUE TITLE
New Chrome timeout issue ?

### ISSUE THREAD

**Issue by VonSzarvas** [parallaxinc/solo#418] opened 2020-04-23 17:15 UTC
Seems after 10 mins or so, many autofill functions stop working, until browser refreshed.

example-- IF control block, click the cog, try adding else block to the structure. It drops in ok, but then click the cog to close the options and the else block didn't appear on the webpage. Refresh browser, then works normally again.

Every options block I've been using today has the same issue.

**Comment by PropGit** [comment] 2020-04-23 17:43
I'm not seeing it on my side.  I'm using Chrome Version 81.0.4044.113

![image](https://user-images.githubusercontent.com/1266318/80131341-f013e380-854e-11ea-8728-3cf47e5c8ebc.png)

![image](https://user-images.githubusercontent.com/1266318/80131354-f609c480-854e-11ea-892f-ca4370a2b8ce.png)

![image](https://user-images.githubusercontent.com/1266318/80131373-ff932c80-854e-11ea-8f77-a2a447cd1be4.png)

![image](https://user-images.githubusercontent.com/1266318/80131431-15a0ed00-854f-11ea-8173-82e0646879e0.png)

At this point, does yours show the Else portion in the in-editor block like mine does above?

![image](https://user-images.githubusercontent.com/1266318/80131399-0883fe00-854f-11ea-82ef-8e2a004bb677.png)

After I click the cog, it looks like the above.

**Comment by VonSzarvas** [comment] 2020-04-23 18:12
your images illustrate well. Try leaving your browser idle over lunch, then try the cog options again - perhaps add another else or elseif and see if they stick.

**Comment by MatzElectronics** [comment] 2020-04-23 18:48
It's possible that the issue is something else.  If there is a javascript error that happened because of something breaking earlier (serial init blocks maybe?), once an error has happened, other stuff can start breaking, which can make these things hard to replicate.

When something goes wrong, if you are able, try capturing the browser console log (although I think we can see that now, so maybe @zfi has some insight?)

**Comment by zfi** [comment] 2020-04-23 19:08
There are a few places in the block definitions that depend on the state of another block to be correct in order to function properly. As @MatzElectronics points out, once that link between blocks fail, we're off to the races as to how many other silent failures can occur. I have seen this with pin assignments and in another case where serial i/o dies because of an intermittent failure in the serial connection to the Launcher/BP Client. 

I have found that opening the developer console before manipulating the blocks is quite instructive in identifying the string of failures. Try to avoid anything that will reload the browser as it will clear the console.

It will be interesting to see if, once we identify a consistent failure pattern, the new code base exhibits the same problem.

**Comment by PropGit** [comment] 2020-04-23 20:46
I've left in for > 1 hr.  Closed the save nag and then added two else ifs (only one else allowed).

![image](https://user-images.githubusercontent.com/1266318/80147684-b9e35d80-8568-11ea-8345-1d2091374407.png)

**Comment by zfi** [comment] 2020-04-24 17:23
@VonSzarvas Can you test this again against the code running on SoloCup and report back if this is still not working there?

**Closed** 2021-01-29 12:39 UTC
