### ISSUE TITLE
Edit project details changes do not persist

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/solo#76] opened 2019-08-31 19:54 UTC
In a given project with a given project name and description, changing the project name and description does not persist.

Example: 
Project Name started as abc, and the Description is test name abc

Click the Hamburger menu
Select Edit Project details

Change the Project Name to def and the description to test name def
Click the Continue button.

The name in the upper-right is still abc, and reopening the Edit Project details option results in the original project name and description, not the updated one.  

Currently, I am able to make the changes persist by using the save project feature to make a local copy.  Next, open it in a text editor, and change the text following Title: and Description: near the end of the file (and then Save).  Finally, use the Open Project button in solo's home page, and the project opens with the correct name def and description of test name def.

**Comment by zfi** [comment] 2019-09-03 21:10
I can confirm that changes in the project details are not preserved between invocations of the Edit Project Details menu item.

The behavior with the project name not changing is expected because the project has not been saved to disk. I do not see where this is documented, so this would be a good opportunity to figure out what the expected behavior should be when the project title is changed after the project is loaded.

**Comment by PropGit** [comment] 2019-09-06 13:06
This appears to be a result of legacy implementation (cloud storage) vs new implementation (local storage).  

Unless we decide to change the UX for managing project details in relation to saved/not-saved, the behavior should be to maintain any changes the user made to such details within the browser session (temporary browser storage) to give the user persistence, just like changes they make to their blocks are persisted in-session.

This will have to be something implemented after the online/offline-behavior code is refactored to a more manageable state.

**Comment by AndyLindsay** [comment] 2019-10-03 17:51
Verified.

**Comment by pjewald** [comment] 2019-10-03 18:35
Thanks @AndyLindsay. 
Closing this issue.

**Closed by pjewald** 2019-10-03 18:35 UTC
Labels: Requires Verification, bug
