### ISSUE TITLE
Arrays not maintaining states (referencing "list" instead of named array)

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/solo#251] opened 2020-01-26 21:26 UTC
In the following video I seem to doubt myself [https://youtu.be/bU2UzQcfAV0](url). 

This code WAS working 100%. I clicked on the array menu from left side. Didn't drag any blocks out - just a click. The states of every single array in use seemed to reset themselves to "list". I do not know if there was a relationship between my action and the loss of state. The errors eventually lead me to fixing every array to point to the correct list name. 

I think this issue has to do with remembering states. Known bug already @MatzElectronics or @PropGit? I don't see it in the current list of issues.

**Comment by MatzElectronics** [comment] 2020-01-27 01:09
Known...ish.  We've battled this a bit, but testing all use cases is
challenging.  Once I'm assigned, I will work to replicate, diagnose, and
fix this.

**Comment by zfi** [comment] 2020-02-28 19:29
@MatzElectronics, Can you report back one you have a determination as to the cause?

**Comment by MatzElectronics** [comment] 2020-03-06 06:27
Got it - the menu contents are getting saved in the mutator, but a the function that builds the menu wasn't being called directly after reloading.  It is being called by a different function who's job is to scan the blocks and rebuild the list of arrays - and that function then called the menu builder.  This gave the block an opportunity to erase its menu.

Instead, the menu builder should be called by the mutator directly, so that the option is present when the fields are populated.

PR is incoming, this one was easy to fix once I found it.

**Comment by zfi** [comment] 2020-06-18 16:58
This is still fundamentally broken. The attached project demonstrates the problem. This is the state of the blocks in the project before it is saved to storage.

<img width="357" alt="Screen Shot 2020-06-18 at 9 53 48 AM" src="https://user-images.githubusercontent.com/8442260/85049610-bffd5100-b149-11ea-9fcf-b1e6f7858706.png">

Loading this same project now renders these blocks. Note that the drop down for the array_fill is no longer myArray but is instead, the default "list" array.

<img width="357" alt="Screen Shot 2020-06-18 at 9 54 12 AM" src="https://user-images.githubusercontent.com/8442260/85049588-b5db5280-b149-11ea-9c1f-da214507e818.png">

This is what is happening at a larger scale in the project reported with this issue.



[Solo-251-0.svg.zip](https://github.com/parallaxinc/solo/files/4799984/Solo-251-0.svg.zip)

**Comment by pjewald** [comment] 2020-06-19 00:30
The array_fill.buildArrayMenu method was reacting poorly to another as-yet undiagnosed issue that is truncating the objects internal array of array variables defined in the project. It was also not preserving the array variable currently assigned to the array_fill block. When the buildArrayMenu method deleted the input field, it is getting replaced with a new input field assigned to the wrong array variable.

Added code to preserve the array variable assignment and to add the array variable name to the internal array list if it was omitted. There is still a problem with the internal array list state.

This issue also appears to impact issue #447 in that the constants used in a switch statement were not preserved correctly across project loads. That issue has also resolved with this update.

**Closed** 2020-06-19 00:59 UTC
Labels: Verified, bug, deployment/staged
