### ISSUE TITLE
Refactor terminal support into a class

### ISSUE THREAD

**Issue by pjewald** [parallaxinc/solo#81] opened 2019-09-15 17:45 UTC
Refactor the terminal code into a class.

**Comment by zfi** [comment] 2019-12-26 20:06
My IDE (WebStorm) is complaining that this.getCharacterSize is an unresolved variable in propterm.js:237.

```
   _getCharacterSize(font) {
        // re-use canvas object for better performance
        let canvas = this.getCharacterSize.canvas || 
            (this.getCharacterSize.canvas = document.createElement("canvas"));
        let context = canvas.getContext("2d");
        context.font = font;
        return context.measureText('AA').width - context.measureText('A').width;
    }

```

Line 380: 'c' is a number and parseint is expecting a string parameter.

```
        c = parseInt(c);
    
```

Line 461: offsetWidth is unknown.

```
                   case 7: // Beep
                        this.element.classList.remove("visual-beep_");
                        j = this.element.offsetWidth;
                        this.element.classList.add("visual-beep_");
```

There are more. This class needs a good review to address a number of type mismatch issues.

**Comment by pjewald** [comment] 2019-12-26 22:44
PR #210 addresses a few of the issues identified after the refactor effort.

**Comment by zfi** [comment] 2020-01-09 23:05
There appears to be an assumption in the Propterm class that the selected DOM element is of a type that supports attributes such as .focus and .blur, but these attributes are unsupported on a generic Element object.

**Comment by zfi** [comment] 2020-01-09 23:46
@MatzElectronics, can you address the remaining TODO's in the propterm.js file?

**Comment by zfi** [comment] 2020-01-14 18:42
There is a pair of unresolved references remaining in the Propterm class. The existing code references a style attribute called overflowY, which is not a valid standard CSS attribute. Any thoughts on why that is being referenced instead of the standard 'overflow' attribute?

Correcting the existing element style references might be as simple as the code below.

```
            this.element.style.overflowY = 'hidden';
            // TODO: recommended replacement
            // this.element.setAttribute('style', 'overflow: hidden');

[...]
            this.element.style.overflowY = 'scroll';
            // TODO: Recommended replacement
            //this.element.setAttribute('style', 'overflow: scroll');
```

**Comment by MatzElectronics** [comment] 2020-01-14 18:48
It is a valid property for an HTML DOM element:
https://www.w3schools.com/jsref/prop_style_overflowy.asp

Its necessary to split up scrolling and treat vertical and horizontal
separately.

**Comment by MatzElectronics** [comment] 2020-01-14 18:49
The CSS equivalent is 'overflow-y'

**Comment by zfi** [comment] 2020-01-14 18:53
Can you correct the two warnings and submit a PR?

**Comment by MatzElectronics** [comment] 2020-01-14 18:54
Sure, I can this afternoon.

**Comment by zfi** [comment] 2020-01-14 20:50
Digging into this a bit more, 'style' is indeed a property of a DOM element. The problem is that the code is not referencing the DOM directly but is instead referencing the DOM API. The API does not have a 'style' property for the Element object. That's where we would use the getAttribute() and setAttribute() methods to manipulate the attributes of the target element.

Reference: https://developer.mozilla.org/en-US/docs/Web/API/Element

**Comment by zfi** [comment] 2020-01-14 20:57
Moving this to the 1.5.0 milestone

**Closed** 2020-02-21 23:21 UTC
Labels: Verified, deployment/staged, task/refactor
